### ISSUE TITLE
Run Don't working with pnpm + WSL 2 (Ubuntu)

### ISSUE THREAD

**Issue by henriqueholtz** [firsttris/vscode-jest-runner#255]
The `Run` don't work with pnpm + WSL 2 (Ubuntu)

- Windows 10
- WSL 2 with Ubuntu 20.04
- PNPM version: 7.1.9
- YARN version: 1.22.18

_(Please, let me know if you need more informations to reproduce.)_

### Details:
If I execute `yarn install`, all works well, but if I execute `pnpm install` I receive the error bellow:

![image](https://user-images.githubusercontent.com/51380783/172801511-1c9fe5ee-667b-4ce7-a348-c4616935fa4c.png)

Thanks.

**Comment by firsttris** [comment]
there are some extension settings for pnpm 
https://github.com/firsttris/vscode-jest-runner#extension-settings

have you checked them?

but no xp with WSL2

**Comment by peterpoliwoda** [comment]
Hi, I've got a similar problem with WSL2. I think what's happening is, the `//wsl\$/Ubuntu/home/` path is not understood by the terminal as wsl itself doesn't know what the //wsl$ alias is (!). 

A way to sort this out would be either to use a relative path or drop the initial //wsl$ passed in to the Terminal 

Errors I'm getting:

```
 $  node "node_modules/jest/bin/jest.js" "//wsl\$/Ubuntu/home/peterpoliwoda/Develop/git/TEC/packages/theme-editor-app/src/pages/translations/hooks/__tests__/utils.spec.ts" -c "//wsl$/Ubuntu/home/peterpoliwoda/Develop/git/TEC/jest.config.js" -t "getParsedStandardTexts"
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: //wsl$/Ubuntu/home/peterpoliwoda/Develop/git/TEC/jest.config.js 
cwd: /home/peterpoliwoda/Develop/git/TEC
    at _default (/home/peterpoliwoda/Develop/git/TEC/node_modules/jest-config/build/resolveConfigPath.js:106:11)
    at readConfig (/home/peterpoliwoda/Develop/git/TEC/node_modules/jest-config/build/index.js:209:49)
    at readConfigs (/home/peterpoliwoda/Develop/git/TEC/node_modules/jest-config/build/index.js:406:32)
    at runCLI (/home/peterpoliwoda/Develop/git/TEC/node_modules/@jest/core/build/cli/index.js:231:29)
    at Object.run (/home/peterpoliwoda/Develop/git/TEC/node_modules/jest-cli/build/cli/index.js:163:62)
    at Object.<anonymous> (/home/peterpoliwoda/Develop/git/TEC/node_modules/jest-cli/bin/jest.js:16:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
``` 

WSL WSL WSL... I realise it may be a slightly different issue but the idea of RUN not working is the same :)

**Comment by henriqueholtz** [comment]
@peterpoliwoda they are differents troubles, really. Because in my terminal don't use `//wsl\$/Ubuntu/home...`, but directly `/home/....`.

I don't can verify the suggestion from @firsttris still.

**Comment by peterpoliwoda** [comment]
How would you run the plugin locally if I was to add a commit to try to fix the issue for certain individuals like myself?
